mobileproject/mobileapp/urls.py
from django.urls import path, include
from . import views

app_name='mobileapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('mobile/<int:mobile_id>/',views.detail,name='detail'),
    path('add/',views.add_mobile,name='add_mobile'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')

]

mobileproject/mobileproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("mobileapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mobileproject/mobileapp/models.py
from django.db import models

# Create your models here.
class Mobile(models.Model):
    model_name=models.CharField(max_length=250)
    price=models.CharField(max_length=250)
    desc = models.TextField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.model_name

mobileproject/mobileapp/forms.py
from django import forms
from . models import Mobile

class MobileForm(forms.ModelForm):
    class Meta:
        model=Mobile
        fields=['model_name','price','desc','img']

mobileproject/mobileapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . models import Mobile
from . forms import MobileForm

# Create your views here.
def index(request):
    mobile=Mobile.objects.all()
    context={
        'mobile_list':mobile
    }

    return render(request,'index.html',context)

def detail(request,mobile_id):
    mobile=Mobile.objects.get(id=mobile_id)
    return render(request,"detail.html",{'mobile':mobile})

def add_mobile(request):
    if request.method=="POST":
        model_name = request.POST.get('model_name')
        price = request.POST.get('price')
        desc = request.POST.get('desc')
        img = request.FILES['img']
        mobile=Mobile(model_name=model_name,desc=desc,price=price,img=img)
        mobile.save()

    return render(request,'add.html')

def update(request,id):
    mobile=Mobile.objects.get(id=id)
    form=MobileForm(request.POST or None, request.FILES, instance=mobile)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'mobile':mobile})

def delete(request,id):
    if request.method=="POST":
        mobile=Mobile.objects.get(id=id)
        mobile.delete()
        return redirect('/')
    return render(request,'delete.html')

mobileproject/templates/add.html
{% extends 'base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}

  <input type="text" name="model_name" placeholder="Enter the mobile name"><br>
  <input type="text" name="price" placeholder="Enter the mobile price"><br>
   <input type="text" name="desc" placeholder="Enter the mobile description"><br>
  <input type="file" name="img"><br>
  <input type="submit">

</form>
{% endblock %}

mobileproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>

<div class="container col-md-12 mb-4">
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="{% url 'mobileapp:index' %}">The Mobile Store</a>
      <a class="navbar-item btn btn-secondary" href="{% url 'mobileapp:add_mobile' %}">Add Movie</a>
  </nav>
</div>

{% block body %}
{% endblock %}

</body>
</html>

mobileproject/templates/delete.html
<form method="POST">
    {% csrf_token %}

    Are you want to delete this mobile?
    <input type="submit">



</form>

mobileproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{mobile.img.url}}" width="250" height="310">
        </div>
        <div class="col-md-6">
            <h4>{{mobile.model_name}}</h4>
            <h5>{{mobile.price}}</h5>
            <h6>{{mobile.desc}}</h6>
            <a class="btn btn-warning" href="{% url 'mobileapp:update' mobile.id %}">update</a>
            <a class="btn btn-danger" href="{% url 'mobileapp:delete' mobile.id %}">Delete</a>
        </div>
    </div>
</div>

{% endblock %}

mobileproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>

mobileproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in mobile_list %}
        <div class="col-md-3 mb-5">
                <div class="card">
                    <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="200" height="310px">
                    <div class="card-body">
                        <h5 class="card-title">{{i.model_name}}</h5>
                        <p class="card-text">{{i.price}}</p>
                        <a href="{% url 'mobileapp:detail' i.id %}" class="btn btn-primary">View Details</a>
                    </div>
                </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}